apiVersion: v1
kind: Service
metadata:
  name: {{ include "bus-reservation.fullname" . }}
  labels:
    {{- include "bus-reservation.labels" . | nindent 4 }}
    serviceLabel: bus-reservation
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  
  selector:
    {{- include "bus-reservation.selectorLabels" . | nindent 4 }}
