apiVersion: v1
kind: Service
metadata:
  annotations: 
    prometheus.io/port: '32473'
    prometheus.io/scrape: 'true'
  name: {{ include "bus-reservation.fullname" . }}
  labels:
    {{- include "bus-reservation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  
  selector:
    {{- include "bus-reservation.selectorLabels" . | nindent 4 }}
